GET http://localhost:3001/users/username
?username=youss
GET http://localhost:3001/users/email?email=hassan@example.com

GET http://localhost:3001/users/67372028031c8c9a26219799

GET http://localhost:3001/users
